# Default initial positions for the servoarm  os2_control fake system
initial_positions:
  base_joint: 0.75049
  platform_joint: 1.0
  lower_joint: 0.017
  top_joint: 0.017
  clawl_joint: 0.017
  hand_joint: 0.017
  eef_joint: 0.017
