# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 5  # Hz
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - base_joint
      - platform_joint
      - lower_joint
      - top_joint
      - eef_joint

hand_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints: 
      - clawl_joint
